updating TZ property documentation
JrCs/docker-crashplan pull request #32
Opened 2016-12-08 07:43 UTC by haysclark

Adding realistic value to quick start and updating the optional environment variables section.
Resolves JrCs/docker-crashplan#31

2016-12-08 11:31 UTC, JrCs requested changes

2016-12-08 11:31 UTC, JrCs commented on README.md
> +  -e TZ=America/Los_Angeles \
Do NOT set the value in the docker run command.
Only use `-e TZ` and docker will use the value set in the environment where it will be start

2016-12-17 11:15 UTC, haysclark commented on README.md
> +  -e TZ=America/Los_Angeles \
`-e TZ` assumes you have the TZ environment variable set, which might not be the case if the host machine is managed by a 3rd party or if the user simply does not have that environment variable set.  A user that does not have their TZ environment variable set is handing 'undefined' to the Docker container because there is no protection in the script. `-e TZ=America/Los_Angeles` works and seems a perfectly normal use case.  I can see both scenarios being used by different users.  Maybe  '-e TZ' does not belong in the 'quick start' example at all.
```
docker run -d \
   --name crashplan \
   -h $HOSTNAME \
   [-e TZ] [-e TZ=<timezone>] \
```

2016-12-30 13:13 UTC, JrCs commented on README.md
> +  -e TZ=America/Los_Angeles \
If you want to force the TZ variable export it's value before calling the docker run command.

2016-12-30 13:24 UTC, JrCs commented
Closed by 8d6fbe524c9f984bc7d8682bbce8e2674b938c82

2016-12-30 13:24 UTC, closed without merging